### ISSUE TITLE
ModuleNotFoundError: No module named 'grp'

### ISSUE THREAD

**Issue by bcarroll** [xolox/python-apache-manager#2]
> OS: Windows 10
> Python = 3.6.4

I installed apache-manager in a fresh virtual environment, ran the apache-manager command and received "ModuleNotFoundError: No module named 'grp'"

Apparently the grp module is not installable via pip.

```
(venv) C:\usr\src\python\DEV>pip list
Package    Version
---------- -------
pip        19.1.1
setuptools 28.8.0
```

```
(venv) C:\usr\src\python\DEV>pip install apache-manager
Collecting apache-manager
  Downloading https://files.pythonhosted.org/packages/51/f6/511d7f40c43e602be1d6fdd680f1a64b225fab45d46abcd820965ff9860a/apache_manager-1.2-py2.py3-none-any.whl
Collecting property-manager>=2.1 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/6f/b6/e6f254334a1a5c8cd0bd0f5b1c44ed7607952e91306b0f569940431897f2/property_manager-2.3.1-py2.py3-none-any.whl
Collecting proc>=0.12 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/b0/07/6a79bf670b21762afe957412a70bfbd6c6395dc22cf8b2bb28634ba89dbd/proc-0.17-py2.py3-none-any.whl (40kB)
     |████████████████████████████████| 51kB 3.2MB/s
Collecting beautifulsoup4>=4.3.2 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl (94kB)
     |████████████████████████████████| 102kB 3.3MB/s
Collecting coloredlogs>=5.2 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/08/0f/7877fc42fff0b9d70b6442df62d53b3868d3a6ad1b876bdb54335b30ff23/coloredlogs-10.0-py2.py3-none-any.whl (47kB)
     |████████████████████████████████| 51kB ...
Collecting humanfriendly>=2.4 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl (73kB)
     |████████████████████████████████| 81kB 5.1MB/s
Collecting six>=1.9.0 (from apache-manager)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting verboselogs>=1.1 (from property-manager>=2.1->apache-manager)
  Downloading https://files.pythonhosted.org/packages/b8/9d/c5c3cb0093642042fd604b53928ac65e7650fdc5a8a97814288e29beab84/verboselogs-1.7-py2.py3-none-any.whl
Collecting executor>=10.0 (from proc>=0.12->apache-manager)
  Downloading https://files.pythonhosted.org/packages/96/21/480c047bdff7b2e8f20ca0f0f3148817bfe1400f2c6bbd3258c710337a63/executor-21.3-py2.py3-none-any.whl (83kB)
     |████████████████████████████████| 92kB 6.1MB/s
Collecting soupsieve>=1.2 (from beautifulsoup4>=4.3.2->apache-manager)
  Downloading https://files.pythonhosted.org/packages/b9/a5/7ea40d0f8676bde6e464a6435a48bc5db09b1a8f4f06d41dd997b8f3c616/soupsieve-1.9.1-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from coloredlogs>=5.2->apache-manager)
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting pyreadline; sys_platform == "win32" (from humanfriendly>=2.4->apache-manager)
  Downloading https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip (109kB)
     |████████████████████████████████| 112kB ...
Collecting fasteners>=0.14.1 (from executor>=10.0->proc>=0.12->apache-manager)
  Downloading https://files.pythonhosted.org/packages/14/3a/096c7ad18e102d4f219f5dd15951f9728ca5092a3385d2e8f79a7c1e1017/fasteners-0.14.1-py2.py3-none-any.whl
Collecting monotonic>=0.1 (from fasteners>=0.14.1->executor>=10.0->proc>=0.12->apache-manager)
  Downloading https://files.pythonhosted.org/packages/ac/aa/063eca6a416f397bd99552c534c6d11d57f58f2e94c14780f3bbf818c4cf/monotonic-1.5-py2.py3-none-any.whl
Installing collected packages: pyreadline, humanfriendly, verboselogs, property-manager, colorama, coloredlogs, monotonic, six, fasteners, executor, proc, soupsieve, beautifulsoup4, apache-manager
  Running setup.py install for pyreadline ... done
Successfully installed apache-manager-1.2 beautifulsoup4-4.7.1 colorama-0.4.1 coloredlogs-10.0 executor-21.3 fasteners-0.14.1 humanfriendly-4.18 monotonic-1.5 proc-0.17 property-manager-2.3.1 pyreadline-2.1 six-1.12.0 soupsieve-1.9.1 verboselogs-1.7
```

```
(venv) C:\usr\src\python\DEV>apache-manager
Traceback (most recent call last):
  File "c:\usr\bin\Python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\usr\bin\Python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\usr\src\python\DEV\venv\Scripts\apache-manager.exe\__main__.py", line 5, in <module>
  File "c:\usr\src\python\dev\venv\lib\site-packages\apache_manager\__init__.py", line 17, in <module>
    from proc.apache import find_apache_memory_usage, find_apache_workers
  File "c:\usr\src\python\dev\venv\lib\site-packages\proc\apache.py", line 37, in <module>
    from proc.tree import get_process_tree, ProcessNode
  File "c:\usr\src\python\dev\venv\lib\site-packages\proc\tree.py", line 39, in <module>
    from proc.core import find_processes, Process
  File "c:\usr\src\python\dev\venv\lib\site-packages\proc\core.py", line 24, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'
```

```
(venv) C:\usr\src\python\DEV>pip install grp
Collecting grp
  ERROR: Could not find a version that satisfies the requirement grp (from versions: none)
ERROR: No matching distribution found for grp
```

**Comment by xolox** [comment]
Hi Brett and thanks for the feedback. I'm sorry to say that `apache-manager` requires Linux and as such does not support Windows. This wasn't documented (my mistake) so I've just committed eb19e3b6834e1c63a9020ab9b00317c495381d10 to explicitly mention this in the first paragraph of the readme.

**Comment by exeptionerror** [comment]
[[Solved] ModuleNotFoundError: No module named ‘grp’ on windows
](https://exerror.com/modulenotfounderror-no-module-named-grp-on-windows/)
